Implement `CairoRunner::segments()` proxy.
lambdaclass/cairo-rs-py pull request #155
Opened 2022-11-24 15:40 UTC by azteca1998

This PR should allow using `runner.segments.<attr-or-method>`-style calls from Python (as in the reference implementation.

2022-11-24 15:46 UTC, Oppen approved these changes

2022-11-28 13:17 UTC, fmoletta requested changes

2022-11-28 15:02 UTC, mmsc2 approved these changes

2022-11-30 18:39 UTC, azteca1998 commented on src/memory_segments.rs
> +    }
Fixed. It now depends on [#637](https://github.com/lambdaclass/cairo-rs/pull/637).

2022-12-22 19:27 UTC, Oppen commented
@fmoletta if your requested changes were satisfied, would you approve and merge this?

2023-01-02 13:54 UTC, fmoletta approved these changes

2023-01-02 14:33 UTC, merged