Add more unit tests for PyIds
lambdaclass/cairo-rs-py pull request #161
Opened 2022-11-28 15:06 UTC by MegaRedHand

This PR adds two new tests and more checks to some unit tests. Also changes `Into::<BigInt>` calls to `bigint!` macro calls.

2022-11-28 15:59 UTC, mmsc2 commented on src/ids.rs
> +            //Err(CustomHint("AttributeError: 'PyTypeId' object has no attribute 'y'"))
delete unnecessary comment

2022-11-28 16:20 UTC, MegaRedHand commented on src/ids.rs
> +            //Err(CustomHint("AttributeError: 'PyTypeId' object has no attribute 'y'"))
Done!

2022-11-28 17:03 UTC, mmsc2 approved these changes

2022-12-01 14:53 UTC, SantiagoPittella requested changes
LGTM, please resolve conflicts and I'll approve it. 🚀

2022-12-01 18:49 UTC, SantiagoPittella approved these changes

2022-12-01 19:07 UTC, merged