Add Uint256 tests
lambdaclass/cairo-rs-py pull request #52
Opened 2022-10-21 20:39 UTC by fmoletta

2022-10-24 22:07 UTC, pefontana requested changes

2022-10-24 22:07 UTC, pefontana commented on cairo_programs/bigint_to_uint256.cairo
> +    %{ ids.low = (ids.x.d0 + ids.x.d1 * ids.BASE) & ((1 << 128) - 1) %}
Add the # TEST tag

2022-10-25 13:17 UTC, fmoletta commented on cairo_programs/bigint_to_uint256.cairo
> +    %{ ids.low = (ids.x.d0 + ids.x.d1 * ids.BASE) & ((1 << 128) - 1) %}
Thanks! I missed it

2022-10-25 15:26 UTC, HermanObst commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test common library hints UINT256](https://trello.com/c/volkcTcl/26-test-common-library-hints-uint256)

2022-10-25 17:52 UTC, pefontana approved these changes

2022-10-27 14:21 UTC, Juan-M-V commented on hints_tests.py
> +    test_program("bigint_to_uint256")
This test throws the error `ValueError: Custom Hint Error: ValueError: Failed to get ids value`, is that expected?

2022-10-27 14:39 UTC, Juan-M-V approved these changes

2022-10-27 14:40 UTC, merged