Add fast_ec_add hint test
lambdaclass/cairo-rs-py pull request #92
Opened 2022-11-01 18:17 UTC by mmsc2

2022-11-01 18:24 UTC, pefontana requested changes

2022-11-01 18:58 UTC, pefontana commented on cairo_programs/fast_ec_add.cairo
> +    let (point_e) = ec_double(EcPoint(BigInt3(156, 6545, 100010), BigInt3(-5336262886225868, 1324, -113834066795297906)))
Lets avoid using the ec_double( function we are not testing here) to create a variable, just define point_e as` point_e = EcPoint(....)`
You can take the paremeters from `cairo_programs/secp_ec.cairo` in cairo_rs

2022-11-03 21:24 UTC, pefontana commented on cairo_programs/fast_ec_add.cairo
> +    let (point_e) = ec_double(EcPoint(BigInt3(156, 6545, 100010), BigInt3(-5336262886225868, 1324, -113834066795297906)))
@mmsc2

2022-11-03 21:24 UTC, pefontana commented on hints_tests.py
> +    # test_program("set_add") # Custom Hint Error: AttributeError: 'builtins.PyMemory' object has no attribute 'get_range'
Don't comment the set_add test

2022-11-04 14:58 UTC, pefontana approved these changes

2022-11-04 15:30 UTC, pefontana commented on cairo_programs/fast_ec_add.cairo
> +    let (point_e) = ec_double(EcPoint(BigInt3(156, 6545, 100010), BigInt3(-5336262886225868, 1324, -113834066795297906)))
Don't worry about this, it is not really necessary

2022-11-04 17:57 UTC, entropidelic approved these changes

2022-11-04 17:57 UTC, merged